name: learningflutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_admob: ^0.9.3+4
  cached_network_image: ^2.2.0+1
  webview_flutter: ^0.3.22+1
  fab_circular_menu: ^1.0.0
  typicons_flutter: ^0.3.1
  page_turn: ^1.0.1
  url_launcher: ^5.5.0

  flutter_share_me: ^0.9.1
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  google_sign_in:
  # Add the dependency for the FlutterFire plugin for Google Analytics
  firebase_analytics: ^5.0.2

  flutter_swiper: ^1.1.6
  neuomorphic_container: ^2.0.3
  curved_navigation_bar: ^0.3.3

  # Add the dependencies for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  firebase_auth:
  cloud_firestore: ^0.12.9+5

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^0.4.0+9
  flutter_keyboard_visibility: ^3.2.1
  flutter_launcher_icons: ^0.7.0




flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/carmicsappiconfivetweleve.png"
  image_path_android: "assets/launcher/carmicsappiconfivetweleve.png"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/qrcode.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Cartoonist
      fonts:
        - asset: fonts/Cartoonist.ttf
    - family: star
      fonts:
        - asset: fonts/star.ttf
    - family: NunitoR
      fonts:
        - asset: fonts/NunitoR.ttf
    - family: Grobold
      fonts:
        - asset: fonts/GROBOLD.ttf
    - family: present
      fonts:
        - asset: fonts/present.ttf

  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
